screaming-fist
==============

An experimental AOT-Compiler for GNU Guile

* PS: tHIS pROJECT IS DELAYED SINCE gUILE'S REGISTER-vm ISN'T DONE YET. iF i DO IT ANY WAY, i'LL DO SOME REGISTER-vm WORK
  ALSO, WHICH IS UNNECESSARY. sO IT DELAYED. bUT IT'LL BE DONE ANYWAY, SINCE IT'S VERY IMPORTANT, UNLESS i'M A DEADMAN, 
  OR IT'LL BE DONE.
